# https://taskfile.dev/
version: "3"

vars:
  PYTHON: python3
  VENVS: .venvs
  FLITENV: "flitenv --venvs={{.VENVS}}"

env:
  FLIT_ROOT_INSTALL: "1"

tasks:
  install:flitenv:
    status:
      - which flitenv
    cmds:
      - "{{.PYTHON}} -m pip install flitenv"
  install:main:
    sources:
      - pyproject.toml
    deps:
      - install:flitenv
    cmds:
      - "{{.FLITENV}} install main"
  install:test:
    sources:
      - pyproject.toml
    deps:
      - install:flitenv
    cmds:
      - "{{.FLITENV}} install test"
  install:lint:
    sources:
      - pyproject.toml
    deps:
      - install:flitenv
    cmds:
      - "{{.FLITENV}} install lint"

  sdk:
    desc: "run a command in the SDK"
    deps:
      - install:main
    cmds:
      - "{{.FLITENV}} run main python3 -m sdk {{.CLI_ARGS}}"
  pytest:
    desc: "run Python tests"
    deps:
      - install:test
    cmds:
      - "{{.FLITENV}} run test pytest {{.CLI_ARGS}}"
  flake8:
    desc: "lint Python code"
    deps:
      - install:lint
    cmds:
      - "{{.FLITENV}} run lint flake8 {{.CLI_ARGS}} ."
  mypy:
    desc: "check type annotations"
    deps:
      - install:lint
    cmds:
      - "{{.FLITENV}} run lint mypy {{.CLI_ARGS}}"
  unify:
    desc: "convert double quotes to single ones"
    deps:
      - install:lint
    cmds:
      - "{{.FLITENV}} run lint unify -r -i --quote=\\' {{.CLI_ARGS}} sdk tests"
  isort:
    desc: "sort imports"
    deps:
      - install:lint
    cmds:
      - "{{.FLITENV}} run lint isort {{.CLI_ARGS}} ."
  isort:check:
    desc: "sort imports"
    deps:
      - install:lint
    cmds:
      - "{{.FLITENV}} run lint isort --check {{.CLI_ARGS}} ."

  # groups
  format:
    desc: "run all code formatters"
    cmds:
      - task: isort
      - task: unify
  lint:
    desc: "run all linters"
    cmds:
      - task: flake8
      - task: mypy
      - task: isort:check
  test:
    desc: "run all tests"
    cmds:
      - task: pytest
  all:
    desc: "run all code formatters, linters, and tests"
    cmds:
      - task: format
      - task: lint
      - task: test
      - "{{.FLITENV}} run main sdk html"
